### PR TITLE
Update outfits - weapons.txt

### PR DESCRIPTION
**Pull request by Alkallid**
It's still here!

### CODE REVIEW

**Comment by Alkallid** [comment]
There.

**Comment by Alkallid** [comment]
Sooo, iis ded?

**Comment by Amazinite** [comment]
Rip

**Comment by Alkallid** [comment]
G'dangit.

**Comment by Amazinite** [comment]
No

**Comment by Alkallid** [comment]
http://i.picpar.com/NnKb.gif

**Comment by Amazinite** [comment]
_sad violin plays_

**Pull request closed without merging**
